language: java
script:
- mvn verify
after_success:
- bash <(curl -s https://codecov.io/bash)
- |
  if [ "$TRAVIS_BRANCH" = 'master' ] || [ -n "$TRAVIS_TAG" ]; then \
    openssl aes-256-cbc -K $encrypted_7e1d625fb9bb_key -iv $encrypted_7e1d625fb9bb_iv -in ci/signing.asc.enc -out ci/signing.asc -d && \
    gpg2 --import ci/signing.asc && \
    mvn deploy -P sign --settings ci/settings.xml
  fi
notifications:
  email:
    recipients:
    - notify@barbatti.de
  on_success: always

