language: java

notifications:
  email:
    recipients:
      - notify@barbatti.de
  on_success: always

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - mvn deploy -s deploy-settings.xml

